# THIS IS A TEMPLATE OF SECRETS.YML
# Use this file as a starting point for your secrets.yml file

# Listed below are the keys required:
#   :secret_key_base
#     Your secret key is used for verifying the integrity of signed cookies.
#     If you change this key, all old signed cookies will become invalid!
#     You can use `rails secret` to generate a secure secret key.
#   :fits_path
#     absolute path to fits.sh executable

# Be sure to restart your server when you modify this file.
# Make sure the secrets in this file are kept private

development:
  fits_path: 'fits.sh'
  secret_key_base: 6d9330537399b2c2b5725c74a0564a76c78ee80b17009998f0a27df02333717fa94f921a259fe6cf97364d9a96c6afb5010aaa5788ebaf8e33e9b1055d54b63a

test:
  fits_path: 'fits.sh'
  secret_key_base: a3fda61f8d10067b196f066d4828b9a4e39b47eb57c2d49129dbf46f43ce0b4f32492c01a7fe68ce471eae9babc23027002ccb20b7fc6ba7069c6c919bd58d96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  fits_path: 'fits.sh'
  secret_key_base: a3fda61f8d10067b196f066d4828b9a4e39b47eb57c2d49129dbf46f43ce0b4f32492c01a7fe68ce471eae9babc23027002ccb20b7fc6ba7069c6c919bd58d96
